[package]
name = "murex-util"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.4"
linux-embedded-hal = "0.3.0"

[features]
default = ["i2c", "uart", "logging"]
i2c = []
uart = []
logging = []
